name: Auto Increment Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "hekimapro"
        git config --global user.email "taprotec@gmail.com"

    - name: Get current tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
        echo "Latest tag: $latest_tag"
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Increment version (patch)
      id: increment_version
      run: |
        current_tag=${{ steps.get_tag.outputs.latest_tag }}
        # Ensure the tag is in the format vX.Y.Z (e.g., v1.0.1)
        if [[ ! "$current_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          echo "Invalid tag format, expected vX.Y.Z, found $current_tag"
          exit 1
        fi
        # Extract major, minor, patch version components
        major=$(echo $current_tag | cut -d. -f1 | tr -d 'v')
        minor=$(echo $current_tag | cut -d. -f2)
        patch=$(echo $current_tag | cut -d. -f3)
        # Increment the patch version
        patch=$((patch + 1))
        new_tag="v$major.$minor.$patch"
        echo "New tag: $new_tag"
        echo "::set-output name=new_tag::$new_tag"

    - name: Create new tag
      run: |
        new_tag=${{ steps.increment_version.outputs.new_tag }}
        echo "Creating new tag: $new_tag"
        git tag $new_tag
        git show-ref --tags  # This will show the tags in the local repository for debugging
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin $new_tag  # Make sure the tag is pushed to the remote

    - name: Push changes
      run: |
        git push origin main  # Ensure both the tag and commit are pushed

